### ISSUE TITLE
Can I unlock the power?

### ISSUE THREAD

**Issue by cyear** [Solaris17/Arc-Firmware#1]
Hello, I have a NUC X15 with Arc A730m GPU. Previously, the power could reach 120W, but currently the highest is only 85W, I have tried all OPROM Data and FW Data, But He even prompts that the version is incorrect，How should I use it？

**Comment by Solaris17** [comment]
In this case it may not work on your specific model. Some like the a370m for example are part of the system bios and not changeable through the tool. I also happen to know that most NUCs pull there BIOS updates from windows update. Its possible that the wattage allowance was modified in a newer revision. In either case this tool won't help you as it is not a discrete card. The only case of a "M" type I have seen work are the "A770M" as it is a retail chip integrated into the NUC but otherwise is the same as its discrete cousin.

Sorry I couldn't be of more assistance.

**Comment by cyear** [comment]
> In this case it may not work on your specific model. Some like the a370m for example are part of the system bios and not changeable through the tool. I also happen to know that most NUCs pull there BIOS updates from windows update. Its possible that the wattage allowance was modified in a newer revision. In either case this tool won't help you as it is not a discrete card. The only case of a "M" type I have seen work are the "A770M" as it is a retail chip integrated into the NUC but otherwise is the same as its discrete cousin.
> 
> Sorry I couldn't be of more assistance.

Okay, thank you very much
