### ISSUE TITLE
OPROM DATA/CODE Are different?

### ISSUE THREAD

**Issue by Toetje585** [Solaris17/Arc-Firmware#2]
I have a Intel Sparkle A750, and I have this:

Device: FW Version: DG02_1.3257
OPROM DATA Version: 14 00 24 04 00 00 00 00
OPROM CODE Version: 14 00 31 04 00 00 00 00
Device: Fw Data Version: Major Version: 101, OEM Manufacturing Data Version: 1, Major VCN: 1

The code firmware is from the latest driver, however the OPROM Data is quite old from Dec 12th, 2022, driver 101.3962 Is this normal?

**Comment by Solaris17** [comment]
This doesn't appear to be about the tool or the repo but overall intel ARC firmware specific updates.

The readme for the tool answers all of this.

https://github.com/Solaris17/ARC-Firmware-Tool/blob/master/docs/guide.md

But yes it can be normal. Partitions of the firmware can be updated while others aren't; and firmware might not be updated at all depending on how the drivers are installed.

Automatic firmware installation is a feature specific to the official ARC installer. It can fail or otherwise not upgrade for several different reasons.
